package proceram;

import java.awt.Dimension;
import java.awt.Font;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

public class caisseframe extends javax.swing.JFrame {

    
     Connection conn =null;
ResultSet rs = null;
PreparedStatement pst = null;
String genre = "dalle de sol";

       int  id = 0, sommetotal= 0 ,sommecrt=0,sommemetres =0;
     float div =0;
            double   mparcrt=0,metrage=0, price =0, rounded=0;
                   


///////////////////////////////////////////////////////////////////
 private ArrayList gettable(){
 
    ArrayList numdata = new ArrayList();
            for (int count = 0; count < id; count++) {
                for (int cl = 0; cl < 6; cl++) {
                    numdata.add(jTable3.getValueAt(count, cl).toString());

                }
                

            }

 return numdata;
 }
    
    
//////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////
 private ArrayList ClientRetoure(){
 
    ArrayList numdatar = new ArrayList();
            for (int count = 0; count < id; count++) {
                for (int cl = 0; cl < 5; cl++) {
                    numdatar.add(jTable3.getValueAt(count, cl).toString());

                }
                    numdatar.add("-"+jTable3.getValueAt(count, 5).toString());
                

            }

 return numdatar;
 }
    
    
//////////////////////////////////////////////////////////////////////////


//////////////////////////////////////////////////////////////////////////////    
    private void UpdateJTable2(){
                  
        String sql = "Select * from stocktable ";
    try{
        pst = conn.prepareStatement(sql);
        rs = pst.executeQuery();
        jTable2.setModel(DbUtils.resultSetToTableModel(rs));
    }
    catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
    }
     jTable2.getColumnModel().getColumn(0).setPreferredWidth(270);
    
    }

    ////////////////////////////////////////////
    
      private void sommetotale(int nbrlines ){
     
      int somtotal =0;
     if (nbrlines == 0){
     jTextField14.setText( jTextField15.getText());
     }
     else{ 
      for (int k =0;k<nbrlines; k++){
      String sum =   jTable3.getModel().getValueAt(k, 5).toString();
      somtotal +=Integer.parseInt(sum) ;
      } 
        jTextField14.setText(String.valueOf(somtotal));
     }
      }
    
    
    ///////////////////////////
    
private void UpdateFields(){
    jTextField10.setText(null); 
    jTextField1.setText(null);
    jTextField2.setText(null);
    jTextField3.setText(null);
    jTextField4.setText(null);
    jTextField7.setText(null);
    jTextField8.setText(null);
    jTextField9.setText(null);
    jTextField6.setText(null);
    jTextField15.setText(null);
    jTextField5.setText(null);
    jTextField13.setText(null);
    jTextField14.setText(null);
}


    
    
    public caisseframe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jTextField13 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jButton8 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(null);

        jPanel5.setOpaque(false);
        jPanel5.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tempus Sans ITC", 1, 20)); // NOI18N
        jLabel4.setText("nom de model");
        jPanel5.add(jLabel4);
        jLabel4.setBounds(10, 20, 134, 27);

        jLabel18.setFont(new java.awt.Font("Tempus Sans ITC", 1, 20)); // NOI18N
        jLabel18.setText("metrage / carton");
        jPanel5.add(jLabel18);
        jLabel18.setBounds(0, 59, 159, 27);

        jLabel26.setFont(new java.awt.Font("Tempus Sans ITC", 1, 20)); // NOI18N
        jLabel26.setText("metrage demende");
        jPanel5.add(jLabel26);
        jLabel26.setBounds(0, 103, 209, 27);

        jLabel12.setFont(new java.awt.Font("Tempus Sans ITC", 1, 20)); // NOI18N
        jLabel12.setText("nombre de carton");
        jPanel5.add(jLabel12);
        jLabel12.setBounds(0, 154, 229, 27);

        jLabel25.setFont(new java.awt.Font("Tempus Sans ITC", 1, 20)); // NOI18N
        jLabel25.setText("cartons arrondis");
        jPanel5.add(jLabel25);
        jLabel25.setBounds(10, 198, 151, 27);

        jLabel10.setFont(new java.awt.Font("Tempus Sans ITC", 1, 20)); // NOI18N
        jLabel10.setText("cartons arrondis/ m");
        jPanel5.add(jLabel10);
        jLabel10.setBounds(0, 244, 186, 27);

        jLabel8.setFont(new java.awt.Font("Tempus Sans ITC", 1, 20)); // NOI18N
        jLabel8.setText("stock / métrés");
        jPanel5.add(jLabel8);
        jLabel8.setBounds(10, 295, 135, 27);

        jLabel7.setFont(new java.awt.Font("Tempus Sans ITC", 1, 20)); // NOI18N
        jLabel7.setText("stock / carton");
        jPanel5.add(jLabel7);
        jLabel7.setBounds(20, 339, 190, 27);

        jLabel5.setFont(new java.awt.Font("Tempus Sans ITC", 1, 20)); // NOI18N
        jLabel5.setText("prix ");
        jPanel5.add(jLabel5);
        jLabel5.setBounds(45, 383, 41, 27);

        jLabel14.setFont(new java.awt.Font("Tempus Sans ITC", 1, 20)); // NOI18N
        jLabel14.setText("somme / m ");
        jPanel5.add(jLabel14);
        jLabel14.setBounds(35, 427, 114, 27);

        jLabel13.setFont(new java.awt.Font("Tempus Sans ITC", 1, 20)); // NOI18N
        jLabel13.setText("somme / carton");
        jPanel5.add(jLabel13);
        jLabel13.setBounds(20, 478, 201, 27);

        jLabel15.setFont(new java.awt.Font("Tempus Sans ITC", 1, 20)); // NOI18N
        jLabel15.setText("somme de facture ");
        jPanel5.add(jLabel15);
        jLabel15.setBounds(10, 554, 171, 27);

        jPanel1.add(jPanel5);
        jPanel5.setBounds(10, 70, 270, 710);

        jPanel4.setBackground(new java.awt.Color(153, 153, 255));
        jPanel4.setOpaque(false);
        jPanel4.setLayout(null);

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jTextField1.setPreferredSize(new java.awt.Dimension(300, 40));
        jPanel4.add(jTextField1);
        jTextField1.setBounds(20, 11, 300, 40);

        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jTextField2.setPreferredSize(new java.awt.Dimension(300, 40));
        jPanel4.add(jTextField2);
        jTextField2.setBounds(20, 57, 300, 40);

        jTextField4.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jTextField4.setPreferredSize(new java.awt.Dimension(300, 40));
        jTextField4.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jTextField4InputMethodTextChanged(evt);
            }
        });
        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField4KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField4KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField4KeyTyped(evt);
            }
        });
        jPanel4.add(jTextField4);
        jTextField4.setBounds(20, 103, 300, 40);

        jTextField3.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jTextField3.setPreferredSize(new java.awt.Dimension(300, 40));
        jPanel4.add(jTextField3);
        jTextField3.setBounds(20, 149, 300, 40);

        jTextField7.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jTextField7.setPreferredSize(new java.awt.Dimension(300, 40));
        jTextField7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField7MouseClicked(evt);
            }
        });
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        jTextField7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField7KeyReleased(evt);
            }
        });
        jPanel4.add(jTextField7);
        jTextField7.setBounds(20, 195, 300, 40);

        jTextField8.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jTextField8.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextField8.setPreferredSize(new java.awt.Dimension(300, 40));
        jPanel4.add(jTextField8);
        jTextField8.setBounds(20, 241, 300, 40);

        jTextField9.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jTextField9.setPreferredSize(new java.awt.Dimension(300, 40));
        jPanel4.add(jTextField9);
        jTextField9.setBounds(20, 287, 300, 40);

        jTextField6.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jTextField6.setPreferredSize(new java.awt.Dimension(300, 40));
        jPanel4.add(jTextField6);
        jTextField6.setBounds(20, 333, 300, 40);

        jTextField15.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jTextField15.setPreferredSize(new java.awt.Dimension(200, 40));
        jTextField15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField15ActionPerformed(evt);
            }
        });
        jTextField15.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField15KeyReleased(evt);
            }
        });
        jPanel4.add(jTextField15);
        jTextField15.setBounds(20, 379, 300, 40);

        jTextField10.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jTextField10.setPreferredSize(new java.awt.Dimension(200, 40));
        jPanel4.add(jTextField10);
        jTextField10.setBounds(20, 425, 300, 40);

        jTextField5.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jTextField5.setPreferredSize(new java.awt.Dimension(200, 40));
        jPanel4.add(jTextField5);
        jTextField5.setBounds(20, 471, 300, 40);

        jTextField14.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jTextField14.setForeground(new java.awt.Color(255, 51, 51));
        jTextField14.setPreferredSize(new java.awt.Dimension(200, 40));
        jTextField14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField14ActionPerformed(evt);
            }
        });
        jPanel4.add(jTextField14);
        jTextField14.setBounds(20, 529, 300, 89);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(266, 70, 270, 610);

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 0, 0));
        jButton7.setText("-");
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);
        jButton7.setBounds(1220, 10, 50, 50);

        jLabel6.setText("jLabel6");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 897, 34, 14);

        jTable2.setAutoCreateRowSorter(true);
        jTable2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTable2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTable2.setRowHeight(50);
        jTable2.setRowMargin(5);
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setResizable(false);
            jTable2.getColumnModel().getColumn(0).setPreferredWidth(300);
        }

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(910, 160, 390, 188);

        jTextField13.setFont(new java.awt.Font("Tempus Sans ITC", 1, 48)); // NOI18N
        jTextField13.setForeground(new java.awt.Color(255, 51, 51));
        jTextField13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField13ActionPerformed(evt);
            }
        });
        jTextField13.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField13KeyReleased(evt);
            }
        });
        jPanel1.add(jTextField13);
        jTextField13.setBounds(620, 160, 260, 70);

        jLabel23.setBackground(new java.awt.Color(0, 0, 0));
        jLabel23.setFont(new java.awt.Font("Tempus Sans ITC", 1, 48)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel23);
        jLabel23.setBounds(550, 240, 340, 110);

        jLabel20.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jLabel20);
        jLabel20.setBounds(550, 170, 0, 50);

        jPanel3.setOpaque(false);

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 22)); // NOI18N
        jButton1.setText("facteurer / client ");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton1.setPreferredSize(new java.awt.Dimension(80, 0));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(204, 204, 204));
        jButton6.setFont(new java.awt.Font("Tempus Sans ITC", 1, 22)); // NOI18N
        jButton6.setText("supprime ");
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(204, 204, 204));
        jButton3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 22)); // NOI18N
        jButton3.setText("annuler ");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(204, 204, 204));
        jButton4.setFont(new java.awt.Font("Tempus Sans ITC", 1, 22)); // NOI18N
        jButton4.setText("imprimer");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(204, 204, 204));
        jButton5.setFont(new java.awt.Font("Tempus Sans ITC", 1, 22)); // NOI18N
        jButton5.setText("Ajouter ");
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 22)); // NOI18N
        jButton2.setText("Retour d'un Client");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(570, 10, 640, 140);

        jTable3.setAutoCreateRowSorter(true);
        jTable3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "numero", "produit", "metrage", "nombre de collis", "prix", "somme"
            }
        ));
        jTable3.setRowHeight(40);
        jScrollPane3.setViewportView(jTable3);
        if (jTable3.getColumnModel().getColumnCount() > 0) {
            jTable3.getColumnModel().getColumn(1).setResizable(false);
            jTable3.getColumnModel().getColumn(1).setPreferredWidth(200);
        }

        jPanel1.add(jScrollPane3);
        jScrollPane3.setBounds(541, 359, 769, 320);

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 0, 0));
        jButton8.setText("x");
        jButton8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8);
        jButton8.setBounds(1270, 10, 50, 50);

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 51));
        jLabel3.setText("nouvelle vente");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 10, 350, 51);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Program Files\\ceramics\\Compass back ground.jpg")); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(-10, 0, 1360, 880);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pieces", "Cartones" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(430, 30, 69, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 693, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

     

    }//GEN-LAST:event_formWindowActivated

    private void jTextField15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField15ActionPerformed

    private void jTextField14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField14ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed


        clientframe clf = new clientframe(id  ,jTextField14.getText() ,  gettable(), null );
        clf.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField13ActionPerformed

    private void jTextField13KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField13KeyReleased

       
      
        String temp = jTextField13.getText() +"%";
        String sql = "select * from stocktable where model like '"+temp+"'";
        try{
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            jTable2.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
        }


             jTable2.getColumnModel().getColumn(0).setPreferredWidth(270);


    }//GEN-LAST:event_jTextField13KeyReleased

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
          
         ImageIcon img = new ImageIcon("C:\\Program Files\\ceramics\\ProCeram.jpg");

       this.setIconImage(img.getImage());
        
        
        conn=ProCeram.ConnectDB();

          UpdateJTable2();
              jTable2.getTableHeader().setFont(  new Font("SansSerif", Font.BOLD, 12));
           jTable3.getTableHeader().setFont(  new Font("SansSerif", Font.BOLD, 12));

           
  jLabel23.setText(java.time.LocalDate.now().toString());           
          
        
        
    }//GEN-LAST:event_formWindowOpened

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
      
        

         int row = jTable2.getSelectedRow();
        jTextField1.setText(jTable2.getModel().getValueAt(row, 0).toString());
        jTextField2.setText(jTable2.getModel().getValueAt(row, 3).toString());
        jTextField9.setText(jTable2.getModel().getValueAt(row, 1).toString());
        jTextField6.setText(jTable2.getModel().getValueAt(row, 2).toString());
        jTextField15.setText(jTable2.getModel().getValueAt(row, 4).toString());
  /////////////////////////////////////////////////////////////////////////////////
  
  //////////////////////////////////////////////////////////////////////////////////////
           genre = jTable2.getModel().getValueAt(row, 5).toString() ;

           jComboBox1.setSelectedItem(genre);
           

////////////////////////////////////////////////////////////////////////////////////////
              
    }//GEN-LAST:event_jTable2MouseClicked

    private void jTextField4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyReleased
 
    metrage  =Double.parseDouble(jTextField4.getText());
        mparcrt =Double.parseDouble(jTextField2.getText());

    div = (float)(metrage / mparcrt);
       jTextField3.setText(String.valueOf(div));
          rounded= Math.round(div);     

       if( div > rounded ){
    rounded +=1;
                   } 

     jTextField7.setText(String.valueOf(rounded));
            jTextField8.setText(String.valueOf((float)(rounded*mparcrt)));
     price=Double.parseDouble(jTextField15.getText());
       sommecrt=(int) (price*rounded*mparcrt);
       sommemetres= (int) (price*metrage);
     jTextField10.setText(String.valueOf(sommemetres));
     jTextField5.setText(String.valueOf(sommecrt));
    }//GEN-LAST:event_jTextField4KeyReleased

    private void jTextField4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyTyped

       

    }//GEN-LAST:event_jTextField4KeyTyped

    private void jTextField4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyPressed

 

    }//GEN-LAST:event_jTextField4KeyPressed

    private void jTextField4InputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jTextField4InputMethodTextChanged




    }//GEN-LAST:event_jTextField4InputMethodTextChanged

    private void jTextField15KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField15KeyReleased

           metrage  =Double.parseDouble(jTextField4.getText());
        mparcrt =Double.parseDouble(jTextField2.getText());

    div = (float) (metrage / mparcrt);
       jTextField3.setText(String.valueOf(div));
              rounded = Double.parseDouble(jTextField7.getText()); 
            jTextField8.setText(String.valueOf((float)(rounded*mparcrt)));
 
       
     price=Double.parseDouble(jTextField15.getText());
       sommecrt=(int) (price*rounded*mparcrt);
       sommemetres= (int) (price*metrage);
     jTextField10.setText(String.valueOf(sommemetres));
     jTextField5.setText(String.valueOf(sommecrt));
   
        
    }//GEN-LAST:event_jTextField15KeyReleased

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        
  /////////////////////////////////////////////
        
        
        jTable3.setValueAt(String.valueOf(id+1), id, 0);
        jTable3.setValueAt(jTextField1.getText(), id, 1);
        jTable3.setValueAt(jTextField8.getText(), id,2);
        jTable3.setValueAt(jTextField7.getText(), id, 3);
        jTable3.setValueAt(jTextField15.getText(), id,4);
        jTable3.setValueAt(jTextField5.getText(), id,5);
     id++;
UpdateFields();
     sommetotale(id );
     
          

    
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed


        for(int i=0 ; i< 30 ;i++){
          for(int j=0 ; j<=5;j++){
        
         jTable3.setValueAt(null, i, j);
      
          }}

        id=0;
        UpdateFields();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

        int selrow =jTable3.getSelectedRow();
        String var=null;
        ///////////////////////////////
        
        if(id == selrow+1 ){
            for(int r =0;r <= 5;r++) {
            jTable3.setValueAt(null, selrow, r);}
              id--;
        }
        else{

            if(id == 0 ){
            jTable3.setValueAt(null, 0, 0);    
           
        }
        else{
            
    for(int j=selrow ; j < id;j++ ){    
       for(int r =0;r <=5;r++){
        var = jTable3.getModel().getValueAt(selrow+1, r).toString();
         jTable3.setValueAt(var, selrow, r);}
          
    }
        //////////////////////////delete last line 
     
       for(int r =0;r <=5;r++){
        
           jTable3.setValueAt(null, id-1, r);
       }
              id--;

              
              for(int z = 1;z<=id ; z++){
               jTable3.setValueAt(String.valueOf(z), z-1, 0);

}
              
        }}
              
              
       ////////////////////////////calculer la somme totale  
        sommetotale( id);
        
        

    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTextField7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7MouseClicked

    private void jTextField7KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField7KeyReleased

        metrage  =Double.parseDouble(jTextField4.getText());
        mparcrt =Double.parseDouble(jTextField2.getText());

    div = (float)(metrage / mparcrt);
       jTextField3.setText(String.valueOf(div));
    
            rounded = Double.parseDouble(jTextField7.getText()); 
            jTextField8.setText(String.valueOf((float)(rounded*mparcrt)));
            price=Double.parseDouble(jTextField15.getText());
    
     sommecrt=(int) (price*rounded*mparcrt);
       sommemetres= (int) (price*metrage);
     jTextField10.setText(String.valueOf(sommemetres));
     jTextField5.setText(String.valueOf(sommecrt));
   
            
            
            
            
      
    }//GEN-LAST:event_jTextField7KeyReleased

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

 
        
        ////////////////////////////////////////////////
    billsframe bf = new billsframe(id,jTextField14.getText(), gettable() ,"Numero de laFacture ","Nom de Client ","0.00",jTextField14.getText()
    
            ,"Societie name"," Societie telephone "," societie adress"," societie site web "
    );
         bf.setVisible(true );
         
         this.dispose();
         
      

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed

   
Compass cmp = new Compass();
cmp.setVisible(true);
this.dispose();
    

    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed


        this.setState(JFrame.ICONIFIED);


    }//GEN-LAST:event_jButton7ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed

         if(jComboBox1.getSelectedItem() == "Pieces"){
        
      jTextField2.setVisible(false);
      jLabel18.setVisible(false);
      
      jLabel26.setText("Nbrs Pieces");
      
      jLabel12.setVisible(false);
      jLabel25.setVisible(false);
      jLabel10.setVisible(false);
      jTextField3.setVisible(false);
      jTextField7.setVisible(false);
      jTextField8.setVisible(false);
     
      jLabel8.setVisible(false);
      jTextField9.setVisible(false);
      
    jLabel7.setText("Stock / Pcs");

      jLabel14.setVisible(false);
      jTextField10.setVisible(false);



    }   else {
        
      jTextField2.setVisible(true);
      jLabel18.setVisible(true);
      jLabel26.setText("metrage demande");
      jLabel12.setVisible(true);
      jLabel25.setVisible(true);
      jLabel10.setVisible(true);
      jTextField3.setVisible(true);
      jTextField7.setVisible(true);
      jTextField8.setVisible(true);
      jLabel8.setVisible(true);
      jTextField9.setVisible(true);
      jLabel14.setVisible(true);
      jTextField10.setVisible(true);
      jLabel7.setText("Stock / Cartones");
        
        
    }
           
           
           
           
  
   //////////////////////////////////////////////////////////////////////////////////
   




    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed


        clientframe clf = new clientframe(id  , jTextField14.getText() ,  ClientRetoure(), "retour" );
        clf.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(caisseframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(caisseframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(caisseframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(caisseframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new caisseframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables

   
}
