/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proceram;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

public class stockframe extends javax.swing.JFrame {

    Connection conn =null;
ResultSet rs = null;
PreparedStatement pst = null;
 SimpleDateFormat formatter1=new SimpleDateFormat("yyyy-MM-dd");  
 boolean typeispiece = false ;   
    
private void UpdateJTable(){
    String sql = "Select * from stocktable ";
    try{
        pst = conn.prepareStatement(sql);
        rs = pst.executeQuery();
        jTable1.setModel(DbUtils.resultSetToTableModel(rs));
    }
    catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
    }
    
     jTable1.getColumnModel().getColumn(0).setPreferredWidth(270);
    
    }
    

private void UpdateFields(){
    
    jTextField1.setText(null);
    jTextField2.setText(null);
    jTextField3.setText(null);
    jTextField7.setText(null);
    jTextField8.setText(null);
    jTextField9.setText(null);
    jComboBox1.setSelectedItem("Cartones");
    jTextField11.setText(null);
    jTextField12.setText(null);
    jTextField14.setText(null);


 try {
            jDateChooser1.setDate(formatter1.parse(java.time.LocalDate.now().toString()));
        } catch (ParseException ex) {
            Logger.getLogger(commandeframe.class.getName()).log(Level.SEVERE, null, ex);
        }   
  
   
}

    
    public stockframe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField14 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setSize(new java.awt.Dimension(700, 600));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setPreferredSize(new java.awt.Dimension(1240, 625));
        jPanel1.setLayout(null);

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(240, 240, 240));
        jPanel1.add(jLabel28);
        jLabel28.setBounds(560, 140, 0, 60);

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(240, 240, 240));
        jPanel1.add(jLabel26);
        jLabel26.setBounds(820, 130, 0, 50);

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTable1.setRowHeight(40);
        jTable1.setRowMargin(3);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTable1MouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(430, 140, 800, 470);

        jTextField14.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jTextField14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTextField14.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField14KeyReleased(evt);
            }
        });
        jPanel1.add(jTextField14);
        jTextField14.setBounds(1010, 70, 211, 60);

        jLabel16.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel16.setText("rechercher un model : ");
        jLabel16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabel16);
        jLabel16.setBounds(810, 70, 250, 70);

        jLabel14.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel14.setText("date appro");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(60, 580, 89, 25);

        jTextField3.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jTextField3.setMinimumSize(new java.awt.Dimension(90, 23));
        jTextField3.setPreferredSize(new java.awt.Dimension(200, 40));
        jPanel1.add(jTextField3);
        jTextField3.setBounds(220, 510, 200, 40);

        jLabel5.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel5.setText("decalage ");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(50, 500, 160, 50);

        jTextField12.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jTextField12.setMaximumSize(new java.awt.Dimension(90, 23));
        jTextField12.setMinimumSize(new java.awt.Dimension(90, 23));
        jTextField12.setPreferredSize(new java.awt.Dimension(200, 40));
        jTextField12.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField12KeyReleased(evt);
            }
        });
        jPanel1.add(jTextField12);
        jTextField12.setBounds(220, 410, 200, 40);

        jLabel11.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel11.setText("stock/ crt");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(50, 420, 84, 25);

        jTextField8.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jTextField8.setMinimumSize(new java.awt.Dimension(90, 23));
        jTextField8.setPreferredSize(new java.awt.Dimension(200, 40));
        jPanel1.add(jTextField8);
        jTextField8.setBounds(220, 460, 200, 40);

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel18.setText("stock /m");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(60, 470, 78, 25);

        jTextField7.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jTextField7.setMinimumSize(new java.awt.Dimension(90, 23));
        jTextField7.setPreferredSize(new java.awt.Dimension(200, 40));
        jTextField7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField7KeyReleased(evt);
            }
        });
        jPanel1.add(jTextField7);
        jTextField7.setBounds(250, 360, 110, 40);

        jLabel13.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel13.setText("metres² /crt");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(70, 355, 160, 40);

        jDateChooser1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jPanel1.add(jDateChooser1);
        jDateChooser1.setBounds(220, 570, 200, 40);

        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jTextField2.setMinimumSize(new java.awt.Dimension(90, 23));
        jTextField2.setPreferredSize(new java.awt.Dimension(200, 40));
        jPanel1.add(jTextField2);
        jTextField2.setBounds(250, 300, 110, 40);

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel3.setText("Nombres pcs/ crt");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(40, 290, 230, 60);

        jLabel6.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel6.setText("prix d achat");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(40, 190, 99, 25);

        jTextField11.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jTextField11.setMinimumSize(new java.awt.Dimension(90, 23));
        jTextField11.setPreferredSize(new java.awt.Dimension(200, 40));
        jPanel1.add(jTextField11);
        jTextField11.setBounds(220, 180, 200, 40);

        jLabel8.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel8.setText("Type");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(60, 250, 120, 25);

        jTextField9.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jTextField9.setMinimumSize(new java.awt.Dimension(90, 23));
        jTextField9.setPreferredSize(new java.awt.Dimension(200, 40));
        jPanel1.add(jTextField9);
        jTextField9.setBounds(220, 120, 200, 40);

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jTextField1.setMinimumSize(new java.awt.Dimension(90, 23));
        jTextField1.setPreferredSize(new java.awt.Dimension(200, 40));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(220, 70, 200, 40);

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel1.setText("nom ");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(100, 60, 46, 50);

        jLabel20.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel20.setText("prix de vent");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(40, 110, 170, 50);

        jLabel9.setFont(new java.awt.Font("Tempus Sans ITC", 1, 48)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setText("Gestion de Magazine");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(50, 0, 530, 64);

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Program Files\\ceramics\\add.png")); // NOI18N
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(440, 70, 60, 60);

        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Program Files\\ceramics\\edite.png")); // NOI18N
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(510, 70, 60, 60);

        jButton3.setIcon(new javax.swing.ImageIcon("C:\\Program Files\\ceramics\\delete.png")); // NOI18N
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(580, 70, 60, 60);

        jButton4.setIcon(new javax.swing.ImageIcon("C:\\Program Files\\ceramics\\refresh-icon323dsa3.png")); // NOI18N
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(650, 70, 60, 60);

        jComboBox1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 28)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cartones", "Pieces" }));
        jComboBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jComboBox1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jComboBox1MouseReleased(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jComboBox1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jComboBox1KeyReleased(evt);
            }
        });
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(220, 240, 200, 50);

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 27)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 102, 102));
        jButton5.setText("x");
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(1160, 10, 60, 50);

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 27)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 102, 102));
        jButton6.setText("-");
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(1100, 10, 60, 50);

        jTextField4.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jTextField4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField4KeyReleased(evt);
            }
        });
        jPanel1.add(jTextField4);
        jTextField4.setBounds(760, 10, 110, 50);

        jButton7.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jButton7.setText("Fitrer");
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);
        jButton7.setBounds(890, 10, 130, 50);

        jLabel4.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel4.setText("Stock < =");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(640, 10, 130, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Program Files\\ceramics\\Compass back ground.jpg")); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 1320, 630);

        getContentPane().add(jPanel1, java.awt.BorderLayout.LINE_START);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        
 
    }//GEN-LAST:event_formWindowActivated

    
    
    
    private void jTextField14KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField14KeyReleased
       
        String temp = jTextField14.getText() + "%";
        String sql = "select * from stocktable where model like'"+temp+"'";
        try{
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));

        }
        catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
        }
        
             jTable1.getColumnModel().getColumn(0).setPreferredWidth(270);

        
    }//GEN-LAST:event_jTextField14KeyReleased

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
       
         int row = jTable1.getSelectedRow();
    
         jTextField1.setText(jTable1.getModel().getValueAt(row, 0).toString());
        jTextField8.setText(jTable1.getModel().getValueAt(row, 1).toString());
        jTextField12.setText(jTable1.getModel().getValueAt(row, 2).toString());
        jTextField9.setText(jTable1.getModel().getValueAt(row, 4).toString());
        jComboBox1.setSelectedItem(jTable1.getModel().getValueAt(row, 5).toString());
        jTextField11.setText(jTable1.getModel().getValueAt(row, 6).toString());
         jTextField2.setText(jTable1.getModel().getValueAt(row, 8).toString());
         jTextField3.setText(jTable1.getModel().getValueAt(row, 9 ).toString());
        
        
   try {
            jDateChooser1.setDate(formatter1.parse(jTable1.getModel().getValueAt(row, 7).toString()));
        } catch (ParseException ex) {
            Logger.getLogger(commandeframe.class.getName()).log(Level.SEVERE, null, ex);
        }
  
           jTextField7.setText(jTable1.getModel().getValueAt(row, 3).toString());

   
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        
        
        conn = ProCeram.ConnectDB();
   UpdateJTable();
   
     ImageIcon img = new ImageIcon("C:\\Program Files\\ceramics\\ProCeram.jpg");

       this.setIconImage(img.getImage());
       
   
   
   
    }//GEN-LAST:event_formWindowOpened

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

////////////////////////////////////////////////////////////////////        
        
        if ( jDateChooser1.getDate()== null){
            
           
 try {
            jDateChooser1.setDate(formatter1.parse(java.time.LocalDate.now().toString()));

            
 } catch (ParseException ex) {
            Logger.getLogger(commandeframe.class.getName()).log(Level.SEVERE, null, ex);
        }   
  
        }
    
        String DateString = formatter1.format(jDateChooser1.getDate());

       
        
////////////////////////////////////////////////////////////////////        
 
         String sql = "insert into stocktable values(?,?,?,?,?,?,?,?,?,?)";
        
         
         try{
            pst = conn.prepareStatement(sql);
            ///////////////////////////////////////////////////S
            ////1 model
            pst.setString(1, jTextField1.getText() );


//////2 stockm
           if(jComboBox1.getSelectedItem()== "Pieces"){
            pst.setString(2, jTextField12.getText()  );
    
}else {
                pst.setString(2, jTextField8.getText()  );

}
          


/////3  stockcrt
            pst.setString(3,  jTextField12.getText() );
            //////4 mcrt
            pst.setString(4,  jTextField7.getText() );
   /////prix taxe 
            pst.setString(5, jTextField9.getText() );
//////// prix vent
            pst.setString(6,  jComboBox1.getSelectedItem().toString() );
//////// prix achat
            pst.setString(7, jTextField11.getText() );
////// date appro
            pst.setString(8, DateString  );
//////  nbrpcs crt
            pst.setString(9, jTextField2.getText() );
/////    nbrcrtplt   
            pst.setString(10,  jTextField3.getText() );
           
 //////////////////////////////////////////////////////////////////////////           
            pst.execute();
            
            JOptionPane.showMessageDialog(null, " * operation reusssite* ");

        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }

            UpdateJTable();
            UpdateFields();




    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        String stockm = null;

        
//////2 stockm
           if(jComboBox1.getSelectedItem()== "Pieces"){
     stockm  =       jTextField12.getText();
    
}else {

   float mcrt = Float.parseFloat(jTextField7.getText()) ;
        float nbrcrt = Float.parseFloat(jTextField12.getText()) ;        
    stockm  =   String.valueOf( mcrt * nbrcrt );
             
               
}
          



     String myday = formatter1.format(jDateChooser1.getDate());

    String sql = "Update  stocktable set model ='" + jTextField1.getText()+ 
            "', stockm= '"+stockm+""
            + "', stockcrt='"+jTextField12.getText()+
            "',mcrt= '"+jTextField7.getText()+
            "',prixtaxe='"+jTextField9.getText()+
            "',genre='"+ jComboBox1.getSelectedItem().toString()+
            "',prixachat='"+jTextField11.getText()+
            "',dateappro='"+myday+
            "',nbrpcscrt='"+jTextField2.getText()+
            "',decalage ='"+jTextField3.getText()+ 
            "' where model  = '"+jTextField1.getText()+" ' ";
        
    ///////////////////////////////////////////////////S
  
 //////////////////////////////////////////////////////////////////////////           
            
    
    try{
            pst = conn.prepareStatement(sql);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, " * L'operation reusssite * ");
            }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        
        UpdateJTable();
        

        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

String sql = "delete * from stocktable where model ='" +jTextField1.getText()+ "'";
        try{
            pst = conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, " * L'operation reusssite * ");
        
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
   
            UpdateJTable();



    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed


    UpdateJTable()    ;

UpdateFields() ;


    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed


   Compass cmp = new Compass();
        cmp.setVisible(true);
        this.dispose();


    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed


this.setState(JFrame.ICONIFIED);

    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTable1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseEntered

    private void jTextField12KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField12KeyReleased

        float mcrt = Float.parseFloat(jTextField7.getText()) ;
        float nbrcrt = Float.parseFloat(jTextField12.getText()) ;
        
jTextField8.setText(String.valueOf( mcrt * nbrcrt ));

    }//GEN-LAST:event_jTextField12KeyReleased

    private void jComboBox1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox1KeyReleased





    }//GEN-LAST:event_jComboBox1KeyReleased

    private void jComboBox1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseReleased



    }//GEN-LAST:event_jComboBox1MouseReleased

    private void jComboBox1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MousePressed

    }//GEN-LAST:event_jComboBox1MousePressed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed


  if (jComboBox1.getSelectedItem()== "Pieces"){
/////// nmb pcs / crt
      jTextField2.setVisible(false);
      jLabel3.setVisible(false);
      jTextField2.setText(null);
      
      ////////// mcrt
      jTextField7.setVisible(false);
      jLabel13.setVisible(false);
      jTextField7.setText("1");
      
       ////////// stock crt
      jLabel11.setText("Nbr Pcs");
      
////////// stock m
      jTextField8.setVisible(false);
      jLabel18.setVisible(false);
      jTextField8.setText(null);
      
////////// decalage
      jTextField3.setVisible(false);
      jLabel5.setVisible(false);
      jTextField3.setText(null);
      
  }  else{

/////// nmb pcs / crt
      jTextField2.setVisible(true);
      jLabel3.setVisible(true);
      jTextField2.setText(null);
      
      ////////// mcrt
      jTextField7.setVisible(true);
      jLabel13.setVisible(true);
      jTextField7.setText(null);
      
       ////////// stock crt
      jLabel11.setText("Stock crt");
      
////////// stock m
      jTextField8.setVisible(true);
      jLabel18.setVisible(true);
      jTextField8.setText(null);
      
////////// decalage
      jTextField3.setVisible(true);
      jLabel5.setVisible(true);
      jTextField3.setText(null);
      

      
  }
////////////////////////////////////////////


    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextField7KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField7KeyReleased

   

    }//GEN-LAST:event_jTextField7KeyReleased

    private void jTextField4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyReleased


    }//GEN-LAST:event_jTextField4KeyReleased

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed

        UpdateJTable()    ;
 ////////////////////////////////////////////////////////////////////////////

int count = 0 , cl = 0 , FilteredProduct=0 , counter =0; 
double value = Double.parseDouble(jTextField4.getText()), tablevalue = 0;
////////////////////////////////////////////////////////////////////////////////////////
      ArrayList numdata = new ArrayList();
         
      for ( count = 0; count < jTable1.getRowCount(); count++) {
            
           tablevalue = Double.parseDouble(jTable1.getValueAt(count, 1).toString());
         if( tablevalue <= value)
                {   
             for ( cl = 0; cl < 10 ; cl++) {
                    numdata.add(jTable1.getValueAt(count, cl).toString());
                   
                  } }   
                    
                
               
                FilteredProduct++;
            }        
/////////////////////////////////////////////////////////////////////////////////  
     DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

/* delete table contentes */
      for ( count = jTable1.getRowCount()-1 ; count >= 0  ; count--) {
          model.removeRow(count);
      }



////////////////////////////////////////////////////////////////////////////////

   
          /////////////////////////////////////////////
     for( count=0; count < FilteredProduct   ;  count++ ){
     

      
model.addRow(new Object[]{ numdata.get(counter), numdata.get(counter+1), numdata.get(counter+2)

                         , numdata.get(counter+3)  , numdata.get(counter+4)  , numdata.get(counter+5) 

                        , numdata.get(counter+6)  , numdata.get(counter+7)  , numdata.get(counter+8) 

                         , numdata.get(counter+9)
});
   
                  counter = counter+10;
                  
              }         
      ////////////////////////////////////////////  
   





/////////////////////////////////////////////////////////////////////////////////////







    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(stockframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(stockframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(stockframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(stockframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new stockframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox<String> jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
